import { Users, Globe, Award, FlaskConical, UserCircle2 } from 'lucide-react';
import { SectionHeader, Particles } from '../components/UI';
const stats=[{val:'500+',label:'Projects',icon:FlaskConical},{val:'50+',label:'Lab Partners',icon:Globe},{val:'99.9%',label:'Uptime',icon:Award},{val:'200+',label:'Researchers',icon:Users}];
const team=[{role:'CEO & Co-Founder'},{role:'CTO'},{role:'VP of Science'},{role:'VP of Engineering'}];
export default function AboutPage(){return(<div>
  <section className="bg-lab-microscope relative flex items-center min-h-[50vh]"><Particles n={5}/><div className="relative z-10 max-w-[700px] mx-auto px-4 sm:px-6 text-center"><p className="text-teal-300 text-xs font-bold tracking-[.15em] uppercase mb-2">About Us</p><h1 className="text-white font-black font-display text-3xl sm:text-4xl mb-3">Pioneering the Future of Biotech Services</h1><p className="text-slate-300 text-base">We're building the infrastructure that connects researchers with the world's best laboratories.</p></div></section>
  <section className="bg-lab-dna py-12 sm:py-16"><div className="max-w-[1200px] mx-auto px-4 sm:px-6"><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{stats.map((s,i)=>(<div key={i} className="bg-white rounded-2xl border border-slate-100 p-5 text-center shadow-md"><div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-600 flex items-center justify-center mx-auto mb-3"><s.icon size={20}/></div><p className="font-black font-display text-slate-900 text-2xl sm:text-3xl">{s.val}</p><p className="text-slate-500 text-xs font-semibold uppercase tracking-wider">{s.label}</p></div>))}</div></div></section>
  <section className="bg-lab-cells py-12 sm:py-16"><div className="max-w-[1200px] mx-auto px-4 sm:px-6"><div className="text-center mb-10"><SectionHeader tag="Our Team" title="Meet the Leaders" desc="The scientists and engineers building the future of biotech."/></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{team.map((t,i)=>(<div key={i} className="bg-white rounded-2xl border border-slate-100 overflow-hidden shadow-md hover:shadow-xl hover:-translate-y-1 transition-all"><div className="h-40 sm:h-48 bg-slate-100 flex items-center justify-center"><UserCircle2 size={72} className="text-slate-300"/></div><div className="p-4 text-center"><h6 className="font-bold font-display text-slate-400 text-sm">— Confidential —</h6></div></div>))}</div></div></section>
</div>);}

